name: V2ex

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: yanglbme/v2ex-action@main
        with:
          webhook: ${{ secrets.WEBHOOK }}
          secret: ${{ secrets.SECRET }}
          count: 8